### ISSUE TITLE
damerau_levenshtein.so (LoadError)

### ISSUE THREAD

**Issue by konzinov** [GlobalNamesArchitecture/damerau-levenshtein#27]
## Description

I cant use the gem after installing it on Amazon Linux 2023 - Ruby 3.2.2 .

## To Reproduce
Actually i am using the Ruby 3.2.2 Platform provided by Aws ElasticBeanstalk.
But i managed to reproduce it with Amazon Linux docker image.

Here are the steps:
```
# run the container
docker run -it amazonlinux:2023 bash
# install build dependencies
yum groupinstall -y "Development Tools" && dnf install -y ruby ruby-devel
# install gem
gem install damerau-levenshtein
# run a test 
ruby -rdamerau-levenshtein -e 'puts DamerauLevenshtein.distance("one", "onne")'

/usr/local/share/ruby3.2-gems/gems/damerau-levenshtein-1.3.3/lib/damerau-levenshtein.rb:4:in `require_relative': libruby.so.2.5: cannot open shared object file: No such file or directory - /usr/local/share/ruby3.2-gems/gems/damerau-levenshtein-1.3.3/lib/damerau-levenshtein/damerau_levenshtein.so (LoadError)
	from /usr/local/share/ruby3.2-gems/gems/damerau-levenshtein-1.3.3/lib/damerau-levenshtein.rb:4:in `<top (required)>'
	from <internal:/usr/share/ruby3.2-rubygems/rubygems/core_ext/kernel_require.rb>:159:in `require'
	from <internal:/usr/share/ruby3.2-rubygems/rubygems/core_ext/kernel_require.rb>:159:in `rescue in require'
	from <internal:/usr/share/ruby3.2-rubygems/rubygems/core_ext/kernel_require.rb>:39:in `require'
<internal:/usr/share/ruby3.2-rubygems/rubygems/core_ext/kernel_require.rb>:85:in `require': cannot load such file -- damerau-levenshtein (LoadError)
	from <internal:/usr/share/ruby3.2-rubygems/rubygems/core_ext/kernel_require.rb>:85:in `require'
```

## Expected behavior
I should get the result 1.
The included .so file seems to reference old libruby.so.2.5
Seems something is not working well on the .so file link after extensions compile step.
Because when i head to the ext/ folder and run `make` command, then copy the generated .so file to src/ folder everything goes well.

Thank you !

**Comment by LocoDelAssembly** [comment]
Just wanted to add that whatever the problem is, it does not apply to all distros:
```
$ docker run -it --rm ruby bash
root@93841d2e962b:/# gem install damerau-levenshtein
Fetching damerau-levenshtein-1.3.3.gem
Building native extensions. This could take a while...
Successfully installed damerau-levenshtein-1.3.3
1 gem installed

A new release of RubyGems is available: 3.5.3 → 3.5.6!
Run `gem update --system 3.5.6` to update your installation.

root@93841d2e962b:/# ruby -rdamerau-levenshtein -e 'puts DamerauLevenshtein.distance("one", "onne")'
1
root@93841d2e962b:/# ruby --version
ruby 3.3.0 (2023-12-25 revision 5124f9ac75) [x86_64-linux]
root@93841d2e962b:/# find -name "libruby*"
./usr/local/lib/libruby.so
./usr/local/lib/libruby.so.3.3.0
./usr/local/lib/libruby.so.3.3
```

**Comment by gautiermorel** [comment]
Hello ! Any updates on this ?

**Comment by dimus** [comment]
Looks like the problem is with Ruby package of the Amazon Linux.  I unstalled rbenv on it, and damerau-levenshtein works fine in this case.

```bash
bash-5.2# yum install -y git-core zlib zlib-devel gcc-c++ patch readline readline-devel libyaml-devel libffi-devel openssl-devel make bzip2 autoconf automake libtool bison  sqlite-devel
bash-5.2# git clone https://github.com/rbenv/rbenv.git ~/.rbenv
bash-5.2# git clone https://github.com/sstephenson/ruby-build.git ~/.rbenv/plugins/ruby-build
bash-5.2#   git clone https://github.com/rkh/rbenv-update.git ~/.rbenv/plugins/rbenv-update

# the following should go to ~/.bashrc (or similar) eventually
bash-5.2# export PATH="$HOME/.rbenv/bin:$PATH"
bash-5.2# eval "$(rbenv init -)"

bash-5.2# rbenv install --list
bash-5.2# rbenv install 3.3.0

bash-5.2# rbenv global 3.3.0
# check the version
bash-5.2# ruby -v 
bash-5.2# gem install damerau-levenshtein
```

Now I run the test:

```bash
bash-5.2# ruby -rdamerau-levenshtein -e 'puts DamerauLevenshtein.distance("one", "onne")'
1
bash-5.2#
```
